### ISSUE TITLE
lint-staged should be in devDependencies?

### ISSUE THREAD

**Issue by llynchIDBS** [TeselaGen/ve-sequence-parsers#12]
Hi - 
I'm running some tools to list our thrid party code and a whole load of npm dependencies seem to be coming through from you guys - way more than before. They don't get seem to get bundled via our use of the lib via npm but are listed by the tooling.
I think it is because "lint-staged" was added as standard dependency but should be in devDependencies ?
Could you take a look please @tnrich ? Let me know if you need more info/help.
Otherwise we've been happily using this - so thanks!

**Comment by tnrich** [comment]
Thanks for the heads up @llynchIDBS. I'm publishing a new version with lint-staged and prettier moved to dev-deps instead of deps. Lemme know if that fixes for you. Thanks!

**Comment by llynchIDBS** [comment]
Yep, that's fixed it - thanks @tnrich !
