### ISSUE TITLE
package is very big

### ISSUE THREAD

**Issue by stropitek** [TeselaGen/ve-sequence-parsers#13]
Hello,

First thank for putting out this useful library on a permissive license.

I'm packaging this library for usage in a web application. I find that because of its dependencies (lodash, xml2js...) the bundle ends up taking almost 1MB after minification just because of bio-parsers.

I think this could be improved quiet easily.

1) Lodash seems superfluous. Only a few methods like `each` are used, which can be easily replaced by vanilla javascript.

2) The package could be splitted in several. This way if I need the genbank parser I don't have the xml2js package bundled with it, since it's not used for that part.

I forked the project and I could work on a PR if you are interested in those improvements.

**Comment by tnrich** [comment]
Hey @stropitek sorry it has taken me so long to get back to you. For some reason I wasn't notified via email for this issue .... 😠  

Yes I think that splitting this package makes sense as well as replacing lodash with vanilla js. I'd love to work together on a PR that can work for everyone.

Let me know when you have a v1 proposal.

**Comment by stropitek** [comment]
Hi @tnrich 
Thanks for coming back to me. I have already created another repo that does just the genbank parsing, with a sync api and with minimal dependencies.

https://github.com/cheminfo-js/genbank-parser

I don't have a lot of resources for this project so I'm going to leave it to that for now.

**Comment by tnrich** [comment]
Hey @stropitek I think in the future this package will probably be upgraded to use es6 at which point webpack (or some other compiler) should be able to handle the tree shaking.
