### ISSUE TITLE
'Buffer is not defined' error in snapgeneToJson.js

### ISSUE THREAD

**Issue by MarcelBolten** [TeselaGen/ve-sequence-parsers#139]
Hi Thomas (@tnrich),

I ran into a problem when using the [snapgeneToJson.js](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/parsers/snapgeneToJson.js) parser.
In particular the error is `Uncaught (in promise) ReferenceError: Buffer is not defined`.
This seems to be associated to an update (it worked before 😉) of the dependencies that are used in the [project](https://github.com/elabftw/elabftw) but I could not identify the specific package so far. It could however locate the [code that triggers the error](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/parsers/snapgeneToJson.js#L33).

In an attempt to make it work again I came across '[The buffer module from node.js, for the browser](https://github.com/feross/buffer)'. If I add it to the dependencies and modify `snapgeneToJson.js` slightly it all works again. I simply added the two lines below as [suggested by the buffer repository](https://github.com/feross/buffer#usage):
```
diff --git a/snapgeneToJson.js b/snapgeneToJson.js
--- a/snapgeneToJson.js
+++ b/snapgeneToJson.js
@@ -11,6 +11,8 @@ import createInitialSequence from './utils/createInitialSequence';
 import validateSequenceArray from './utils/validateSequenceArray';
 import flattenSequenceArray from './utils/flattenSequenceArray';

+var Buffer = require('buffer/').Buffer
+
 async function snapgeneToJson(
   fileObj,
   onFileParsedUnwrapped,
``` 
Maybe it should be [extended similarly as done somewhere else](https://github.com/agoncal/swagger-ui-angular6/issues/2#issuecomment-435307286).
Or maybe there is another solution that you can suggest. If not, would you be willing to merge a PR with this changes?

Cheers,
Marcel

**Comment by tnrich** [comment]
Hey @MarcelBolten it sounds like you're experiencing this when using ve-sequence-parsers in the browser, correct?

**Comment by MarcelBolten** [comment]
Yes, that is right.

**Comment by tnrich** [comment]
@MarcelBolten I've implemented the fix you suggested. Let me know if that fixes things for you. https://github.com/TeselaGen/ve-sequence-parsers/commit/8ed0fca025b429f478f776ca544879341e616d19

**Comment by MarcelBolten** [comment]
Thanks for the fix. I will test it.

The error should be related to a webpack 5 upgarde. In particular to the [Changes to the Structure]( https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure): 
> Automatic polyfills for native Node.js modules were removed
> - node.Buffer removed

**Comment by MarcelBolten** [comment]
Seems to work perfectly.
Thank you very much!
