### ISSUE TITLE
Understanding package releases

### ISSUE THREAD

**Issue by chrisvaillancourt** [TeselaGen/ve-sequence-parsers#149]
@tnrich 

Hello!

First off, thank you for your excellent work on this package. 

Do you make any release notes available for published package versions? The [changelog](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/Changelog.md) isn't current and I can't find other resources for understanding the implications of updating to the latest version.

I don't have a background in bio so any help understanding the commit history would be greatly appreciated.

**Comment by tnrich** [comment]
Hey @chrisvaillancourt ! 

We should really be updating the changelog for all the releases. I can try to add a description for each release retroactively. Which version are you on currently? 

Thanks! 
Thomas

**Comment by tnrich** [comment]
@chrisvaillancourt I've updated the changelog to add descriptions of some of the more notable changes. I'll try to do a better job of updating the changelog in the future.

**Comment by tnrich** [comment]
Hey @chrisvaillancourt I've added a more robust, auto-generated changelog https://github.com/TeselaGen/ve-sequence-parsers/blob/master/Changelog.md 

I'll do my best to make the commit messages understandable as they're used directly in the changelog. Cheers!

**Comment by chrisvaillancourt** [comment]
Thank you so much! This is really helpful.
