### ISSUE TITLE
Ambiguous AA handling X vs - chars

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/ve-sequence-parsers#153]
Hi @tnrich ,

I noticed that Ambiguous AA 'X' are not rendered.

![image](https://user-images.githubusercontent.com/10584220/105626379-7edfc480-5e2f-11eb-976a-6d6725605ddb.png)

I used this fix. But may not work where proteinAlphabet["-"] is used.

```
  if (threeLetterSequenceStringToAminoAcidMap[sequenceString]) {
    return threeLetterSequenceStringToAminoAcidMap[sequenceString];
  } else  {
    return proteinAlphabet["X"];
  } 
//else {
//    return proteinAlphabet["-"]; //return a gap/undefined character
 // }

```

_Originally posted by @kelmazouari in https://github.com/TeselaGen/ve-sequence-parsers/discussions/140#discussioncomment-305942_

**Comment by tnrich** [comment]
@kelmazouari I'm looking at the code you referenced. It seems like there needs to be more logic here to determine when the three letter DNA code coming in should be one of the following AA's or an X or a gap character. 

B: ND
J: IL
X: ACDEFGHIKLMNPQRSTVWY 
Z: QE
"-": gap char
".": gap char

I've added logic to handle those cases better to ve-sequence-utils and published a major version there. I'll update bio-parsers and ove with this update and let you know when those have been released.

Here's what the new logic looks like: 
``` js
let aa = threeLetterSequenceStringToAminoAcidMap[sequenceString];
  if (aa) {
    return aa;
  }
  const letter =
    degenerateDnaToAminoAcidMap[
      sequenceString.replace("x", "n") //replace x's with n's as those are equivalent dna chars
    ] || "x";
```

**Comment by kelmazouari** [comment]
Hi @tnrich 
IMHO, and sorry if I am using some Java keyword; I think the meaning is the still the same in JS
If my DNA seq contains an 'X', I will throw an Exception.
In case of a valid codon, like above (TNT), I will return an ambiguous AA.
I will also not mix '-' and '.' with translation char/String: AA, X and *
I guess '-' and '.' are used in further seq processing, maybe multiple alignments (I didn't check). I will move them out of the AA list. Creating a new class that extends the AA and includes '-',  '.' and  '*' will give me more flexibility. Please notice that a '*' may have a different meaning. It's a stop in a translation, and multiple alignments is a non-consensus AA or NT.

**Comment by kelmazouari** [comment]
Hi @tnrich 
IMHO, and sorry if I am using some Java keyword; I think the meaning is the still the same in JS
If my DNA seq contains an 'X', I will throw an Exception.
In case of a valid codon, like above (TNT), I will return an ambiguous AA.
I will also not mix '-' and '.' with translation char/String: AA, X and *
I guess '-' and '.' are used in further seq processing, maybe multiple alignments (I didn't check). I will move them out of the AA list. Creating a new class that extends the AA and includes '-',  '.' and  * will give me more flexibility. Please notice that a * may have a different meaning. It's a stop in a translation, and in multiple alignments is a non-consensus AA or NT.

**Comment by tnrich** [comment]
Hey @kelmazouari 

I am taking X as a valid dna character. I am mostly using this chart here to make my ambiguous letter determinations: 

![image](https://user-images.githubusercontent.com/2730609/106025820-fa36b580-607d-11eb-8431-72596998d13f.png)

https://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html

From what I can tell by comparing with other sources, that chart seems fairly accurate. 

Is the new parser logic not working for you for a specific case or were you just pointing out that you do things differently in your code? 

Thanks!
Thomas

**Comment by kelmazouari** [comment]
Thanks @tnrich,
That was just my own suggestion based on another project I am working. 
The new parser is working fine.
