### ISSUE TITLE
Parsing Genbank circular sequence

### ISSUE THREAD

**Issue by kelmazouari** [TeselaGen/ve-sequence-parsers#154]
@tnrich 
anyToJson sequenceData.circular is false for Genbank circular sequence.

**Comment by tnrich** [comment]
@kelmazouari good find! Can you provide a genbank file for which this behavior is happening? If so I'll look into it :)

**Comment by kelmazouari** [comment]
@tnrich 
This problem is probably related to LOCUS, which is in 2 lines. In the past, LOUCS was always one line, which makes the parsing simple.
However, sometimes LOCUS can be two lines. For some parsers, it's a problem.
Hope this will help
[ove-test-gb.txt](https://github.com/TeselaGen/ve-sequence-parsers/files/5926883/ove-test-gb.txt)

**Comment by tnrich** [comment]
@kelmazouari this should be fixed in bio-parsers@7.0.3 

Let me know if that works for you :)

**Comment by kelmazouari** [comment]
Fixed - thanks
