### ISSUE TITLE
Sequence type parsed from a genbank file to be more concrete

### ISSUE THREAD

**Issue by grigoll** [TeselaGen/ve-sequence-parsers#161]
Hi there and thank you for this library.

When I'm parsing genbank file (e.g. [this one](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/test/testData/genbank/CCR5_multifrag_insert1.gb)), returned sequence type is DNA, but I need it to be a bit more concrete as it's in the `LOCUS` field of the file, in the file example - `ds-DNA`.
From what I've checked the source at a glance, it looks like the sequence type is not parsed from THE field, but it's determined by [the logic](https://github.com/TeselaGen/ve-sequence-parsers/blob/4d262c56a52c07324a2969e8de564f94a5a2d5cd/src/parsers/utils/validateSequence.js#L91).

It would be great if we could support parsing it from THE field. WDYT @tnrich ?

Thank you.

**Comment by tnrich** [comment]
Hey @grigoll I've added a new `result.parsedSequence.sequenceTypeFromLocus` field that is detected and parsed off using the following logic: 
```
item.match(/ds-dna/i) || item.match(/ss-dna/i) || item.match(/dna/i)
```

The change was introduced in this commit: 
https://github.com/TeselaGen/ve-sequence-parsers/commit/62d3b93783c11461534f41095b2cb1fdc11f0162

**Comment by grigoll** [comment]
@tnrich yes this is what I was looking for and it worked. Good work man, thanks.
Closing the issue.
