### ISSUE TITLE
Don't console.log options when parsing FASTA

### ISSUE THREAD

**Issue by Benjamin-Lee** [TeselaGen/ve-sequence-parsers#183]
This looks like a mistake left in from debugging:
https://github.com/TeselaGen/ve-sequence-parsers/blob/c69de505c3a3e7d08553c254408fb7af8e931da6/src/parsers/fastaToJson.js#L13

**Comment by tnrich** [comment]
@Benjamin-Lee thanks for letting me know. It's been removed in bio-parsers@8.3.11
