### ISSUE TITLE
Suggestion: don't try to parse FASTA header lines (or make an option to turn it off)

### ISSUE THREAD

**Issue by Benjamin-Lee** [TeselaGen/ve-sequence-parsers#185]
@tnrich 

Right now, when parsing a [standard NCBI header line](https://en.wikipedia.org/wiki/FASTA_format#NCBI_identifiers) such as `gb|M73307|AGMA13GT` , the sequence "name" is set as the first thing before the pipe: `gb`. This is due to this function:

https://github.com/TeselaGen/ve-sequence-parsers/blob/ce59fbffc698407cb4578ba2d21a55eb20c1ea86/src/parsers/fastaToJson.js#L73-L81

Given the fact that FASTA headers are completely inconsistent and a mess, I would suggest skipping header parsing altogether or at least making it able to be disabled. If feeling fancy, one could pass a parser function that would return `{name, description}` so the user could decide.

**Comment by tnrich** [comment]
@Benjamin-Lee could you put in a PR with the change you'd like to see for this? I agree that fasta headers are quite a jumble.

**Comment by Benjamin-Lee** [comment]
Do you care if it’s a breaking change? Or should it be backwards compatible?

**Comment by tnrich** [comment]
Ideally it should be backwards compatible

**Comment by tnrich** [comment]
Is that ok with you @Benjamin-Lee ?

**Comment by tnrich** [comment]
@Benjamin-Lee sending you a friendly bump on this one :)
