### ISSUE TITLE
is possible a JS?

### ISSUE THREAD

**Issue by Sanrrone** [TeselaGen/ve-sequence-parsers#186]
@tnrich 
Dears,
I am not an advanced web developer and my efforts on import the file as you describe is not working in my case. I think neither most of biologist does not have the skills to do it. Could you consider JS version to import it in our files?.

thanks in advance

**Comment by tnrich** [comment]
@Sanrrone I assume you're asking for a way to use the module from a <script> tag? This is indeed possible. I'll add more documentation of how to do that.

**Comment by Sanrrone** [comment]
That would be awesome.
I'll keep open the ticket waiting for the update.

thanks!

**Comment by tnrich** [comment]
Hey @Sanrrone I've updated the docs here with an example: https://github.com/TeselaGen/ve-sequence-parsers#usage

**Comment by Sanrrone** [comment]
the sky is the limit now hehehe.
