### ISSUE TITLE
Parse basic html used in description field from Snapgene plasmid sequences

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve-sequence-parsers#225]
@tnrich it looks like Snapgene very commonly uses a bit of HTML in their description fields. We should perhaps interpret instead of being literal? Maybe we convert at import?

Use case: All of the [plasmids available from Snapgene](https://github.com/TeselaGen/lims/issues/8893) have this issue with the description field. These consist of **2,700** carefully annotated plasmid and sequence files including commonly used cloning vectors from all major suppliers.

![image](https://user-images.githubusercontent.com/7561861/158743029-977348e2-4fb0-42bd-a1e6-5ebcedbb2c14.png)
![image](https://user-images.githubusercontent.com/7561861/158743220-9512bb52-3683-41d9-bce0-6452f6f34926.png)

**Comment by mfero** [comment]
Here is an example .dna file from Snapgene which has the extra bit of HTML in the description field. [This is the link to the source of these plasmids.](https://www.snapgene.com/resources/plasmid-files/
[SnapgeneExampleDNAFiles.zip](https://github.com/TeselaGen/ve-sequence-parsers/files/8306538/SnapgeneExampleDNAFiles.zip)
)

**Comment by tnrich** [comment]
This has been fixed and released!
