### ISSUE TITLE
V_region is not parsed

### ISSUE THREAD

**Issue by solenevEPAM** [TeselaGen/ve-sequence-parsers#4]
V_region is not parsed because there is a space in the end of it in parsers/utils/GenbankFeatureTypes.js

Currectly V_region is being parsed as Misc. Feature

**Comment by solenevEPAM** [comment]
Also there is 'old_sequence' type of feature which is missing in the current list

**Comment by tnrich** [comment]
Hey @solenevEPAM thanks for the great feedback! If you made a PR for those two things I'd be happy to accept them!

**Comment by tnrich** [comment]
@solenevEPAM version 4.3.2 is now released with this fix

**Comment by solenevEPAM** [comment]
Awesome, thank you!
