### ISSUE TITLE
I got error when installing bio-parsers. npm ERR! Invalid dependency type requested: alias

### ISSUE THREAD

**Issue by zhangxiang36** [TeselaGen/ve-sequence-parsers#45]
@tnrich 
I got error when I run command"npm install -S bio-parsers"
npm ERR! Invalid dependency type requested: alias
node log file is shown as below.
What can i do to avoid this error?Is there any problem with my node or npm version? Thanks.
[2019-09-09T07_27_44_457Z-debug.log](https://github.com/TeselaGen/ve-sequence-parsers/files/3589131/2019-09-09T07_27_44_457Z-debug.log)

**Comment by tnrich** [comment]
Hey @zhangxiang36 I'll take a look now

**Comment by tnrich** [comment]
@zhangxiang36 it looks to me like it's coming from: 
```
"@types/lodash": "npm:@types/lodash-es",
```

I'll try adding that _not_ as a dependency but as a dev dependency and publish a new version.

**Comment by tnrich** [comment]
@zhangxiang36 try `bio-parsers@5.6.2` (the latest version) and let me know if that works for you. Thanks!

**Comment by tnrich** [comment]
@zhangxiang36 it works for me with npm v6.9.0 :  
```
npm -v
6.9.0
thomass-mbp:wheels tnrich$ npm i -S bio-parsers@latest
npm WARN bio-parsers@5.6.3 requires a peer of ve-range-utils@^2.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN bio-parsers@5.6.3 requires a peer of ve-sequence-utils@^3.2.19 but none is installed. You must install peer dependencies yourself.
npm WARN wheels@1.0.0 No description

+ bio-parsers@5.6.3
added 6 packages from 6 contributors, updated 3 packages, moved 2 packages and audited 81 packages in 5.187s
found 0 vulnerabilities
```

**Comment by zhangxiang36** [comment]
Sorry to late reply. i'll try again.

**Comment by zhangxiang36** [comment]
OK, it works now!! Thank you !
