### ISSUE TITLE
Browserfied version

### ISSUE THREAD

**Issue by zachcp** [TeselaGen/ve-sequence-parsers#6]
Hi Team Teselagen,

I've stumbled across your repos while looking for genbank parsers and I am very impressed.  Great work. 

I would be interested in using this library in pure browser (not node) application. Is there any chance that you have these libraries in browserified format (preprocessed; minimized)? If not, I believe this would be a useful format if you have the time/bandwidth.

Thanks,
zach cp

**Comment by tnrich** [comment]
Hey @zachcp sorry for the super delayed response. This repo can be used in browserify/webpack as "bio-parsers" on npm: https://www.npmjs.com/package/bio-parsers

Hope that helps! Let me know if you run into any issues using it :)
