### ISSUE TITLE
genbankToJson parser crops any feature string containing a "=".

### ISSUE THREAD

**Issue by Zulko** [TeselaGen/ve-sequence-parsers#79]
Hi there and thank you for this library. I am parsing Genbanks with it and I noticed that every label containing a "=" gets cut out after the "=". I believe this is because of the following line, which simply takes the second argument (but not any subsequence element) after the line split:

https://github.com/TeselaGen/ve-sequence-parsers/blob/99641ea2a4984c01cf42526104b648e850da53e3/lib/parsers/genbankToJson.js#L482-L483

I believe replacing ``return arr[1]`` by ``return arr.slice(1).join('')`` would solve the problem.

**Comment by tnrich** [comment]
Hey @Zulko thanks for the heads up! I'll fix that and let you know when it's released :)

**Comment by tnrich** [comment]
@Zulko I just released `bio-parsers@6.0.1` on npm. Let me know if that resolves your issue. Here's the commit where I changed the code (your fix didn't quite work but it was close) and added a test: https://github.com/TeselaGen/ve-sequence-parsers/commit/79c02c285617f1e3e42a32bb4de8f055d0d97b5a

**Comment by Zulko** [comment]
Thank you so much! I will try it in the next few days and confirm, but the tests look good to me!

**Comment by tnrich** [comment]
I'll close this. Please feel free to re-open or create a new issue if you need any help :)
