### ISSUE TITLE
[Q] How to check whether the fasta sequence is protein or nucleic?

### ISSUE THREAD

**Issue by abaranovskiyidbs** [TeselaGen/ve-sequence-parsers#9]
Hi. Sorry for posting the question here,didn't find another good place to ask.
[validateSequence](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/parsers/utils/validateSequence.js#L16) accepts `isProtein` option to validate sequence characters [properly](https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/parsers/utils/validateSequence.js#L53-L76):

    if (isProtein) {
        ...
     } else {
        ...
     }

I'm wondered, is there strong way to check whether the fasta sequence is protein or nucleic by looking at it to provide valid `isProtein` option to this method?

For example I've got the following fasta sequence and I need to know either this is protein or not:
```
>gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus maximus]
LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGTNLV
EWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFHPYYTIKDFLG
LLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLALFLSIVIL
GLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGX
IENY
```
Any help will be appreciated!

**Comment by tnrich** [comment]
Hey @abaranovskiyidbs it sound like it would be a good idea if I add an option to make the parsers guess if the incoming sequence is protein or dna. 

Are you currently trying to import a mix of DNA and AA sequences without knowing what type they are beforehand?

**Comment by tnrich** [comment]
@abaranovskiyidbs I've added a new option that you should be able to use to determine if a sequence is of type `PROTEIN` or `DNA` 

```
guessIfProtein: false, //if true the parser will attempt to guess if the sequence is of type DNA or type PROTEIN (this will override the isProtein flag)
 ```

There are more options layed out here: 
https://github.com/TeselaGen/ve-sequence-parsers#useage

**Comment by llynchIDBS** [comment]
Thanks @tnrich - looks like exactly what we wanted, and those finer options look useful. I think that's esp useful with FASTA files as there's generally no indication apart from the content (biojava has a similar heuristic detection thing going on I believe). Re your genbank parsing - do you know if this will deal correctly with genpept files? I.e. will using genbankToJson with isProtein=true correctly parse a genpept file? I think the formats are virtually identical.

**Comment by tnrich** [comment]
@llynchIDBS Yes this should work for genpept files. Please let me know if you hit any issues with using it though :)
